In [1]:
import requests 
from bs4 import BeautifulSoup
import pandas as pd

In [6]:
with open('30 Most Popular Movies.html', 'r', encoding='utf-8') as file:
    content = file.read()
soup = BeautifulSoup(content,'html.parser')
box=soup.find_all('div',class_="article_movie_title")
names=[]
rating=[]
for i in box:
    names.append(i.find('a').text.strip())
    rating.append(i.find('span', class_='tMeterScore').text.strip())
movies={'name':names, 'rating':rating}
df=pd.DataFrame(movies)
df

                                       name rating
0          Transformers: Rise of the Beasts    53%
1       Spider-Man: Across the Spider-Verse    96%
2                        The Little Mermaid    67%
3                             The Boogeyman    63%
4     Are You There God? It's Me, Margaret.    99%
5                                    Fast X    56%
6                                BlackBerry    98%
7                               The Machine    27%
8                                   Reality    92%
9                               Flamin' Hot    68%
10           Guardians of the Galaxy Vol. 3    82%
11                                Blue Jean    94%
12                               Past Lives    97%
13              The Super Mario Bros. Movie    58%
14                 Avatar: The Way of Water    76%
15               Guy Ritchie's The Covenant    83%
16                                Bumblebee    91%
17                                Nefarious    33%
18                                     Sisu    93%
19                     You Hurt My Feelings    95%
20                     John Wick: Chapter 4    94%
21                           Leave No Trace    80%
22                          About My Father    36%
23  Dungeons & Dragons: Honor Among Thieves    90%
24                             Transformers    57%
25                                 My Fault
26                         A Beautiful Life    50%
27     The Angry Black Girl and Her Monster    88%
28                                  Missing    87%
29                                      Air    92%

In [13]:
# car name, mileage, price, rating
with open('Certified used Mercedes-Benz for sale.html', 'r', encoding='utf-8') as file:
    content = file.read()
soup = BeautifulSoup(content,'html.parser')
box=soup.find_all('div',class_="vehicle-details")
names=[]
mileage=[]
price=[]
rating=[]
for i in box:
    names.append(i.find('h2',class_='title').text.strip())
    mileage.append(i.find('div',class_='mileage').text.strip())
    price.append(i.find('span',class_='primary-price').text.strip())
    r=i.find('span', class_='sds-rating__count')
    if(r):
        rating.append(r.text.strip())
    else:
        rating.append(0)
cars={'name':names, 'mileage':mileage, 'price':price, 'rating':rating}
df=pd.DataFrame(cars)
df

                                            name     mileage     price rating
0         2020 Mercedes-Benz CLA 250 Base 4MATIC  28,744 mi.   $35,995    4.4
1              2019 Mercedes-Benz AMG GT 53 Base  25,771 mi.   $79,995    4.0
2             2021 Mercedes-Benz AMG GLE 53 Base  22,374 mi.   $80,923    2.8
3      2022 Mercedes-Benz AMG CLA 45 Base 4MATIC  10,595 mi.   $56,633      0
4             2021 Mercedes-Benz AMG GLE 53 Base  33,622 mi.   $76,995    4.7
5        2021 Mercedes-Benz E-Class E 450 4MATIC  12,477 mi.   $76,532    4.5
6   2021 Mercedes-Benz AMG GLE 63 S-Model 4MATIC  22,383 mi.  $102,990    4.8
7               2019 Mercedes-Benz S-Class S 560  49,332 mi.   $54,580    4.8
8             2021 Mercedes-Benz AMG GLE 53 Base  37,688 mi.   $76,715    2.8
9                2021 Mercedes-Benz GLA 250 Base  19,521 mi.   $34,999    4.6
10       2022 Mercedes-Benz AMG C 43 Base 4MATIC  14,420 mi.   $62,991    4.8
11       2018 Mercedes-Benz AMG C 43 Base 4MATIC  34,555 mi.   $39,999    4.4
12       2021 Mercedes-Benz E-Class E 450 4MATIC  16,474 mi.   $74,998    4.8
13       2021 Mercedes-Benz S-Class S 580 4MATIC  10,233 mi.   $99,822    4.5
14         2022 Mercedes-Benz GLE 450 AWD 4MATIC   6,800 mi.   $73,990    4.8
15        2018 Mercedes-Benz GLC 300 Base 4MATIC  54,467 mi.   $29,151    4.5
16            2022 Mercedes-Benz AMG GLA 35 Base   8,690 mi.   $49,736    4.5
17               2022 Mercedes-Benz GLB 250 Base   8,158 mi.   $42,000    4.1
18       2022 Mercedes-Benz S-Class S 500 4MATIC   8,401 mi.   $86,986    4.5
19       2020 Mercedes-Benz AMG S 63 Base 4MATIC  24,958 mi.  $105,997    4.8
20        2021 Mercedes-Benz GLC 300 Base 4MATIC  49,278 mi.   $37,280    4.2

In [27]:
with open('flipkart.html', 'r', encoding='utf-8') as file:
    content = file.read()
soup = BeautifulSoup(content,'html.parser')
box=soup.find_all('div',class_="_3pLy-c row")
names=[]
rating=[]
a_price=[]
d_price=[]
diff=[]
for i in box:
    names.append(i.find('div',class_='_4rR01T').text.strip())
    rating.append(i.find('div',class_='_3LWZlK').text.strip())
    d=i.find('div',class_='_30jeq3 _1_WHN1').text.strip()
    d_price.append(d)
    a=i.find('div', class_='_3I9_wc _27UcVY')
    if(a):
        a_price.append(a.text.strip())
        dif= int(a.text.strip().replace('₹','').replace(',','')) - int(d.replace('₹','').replace(',',''))
        diff.append(dif)
    else:
        a_price.append(0)
        diff.append(int(d.replace('₹','').replace(',','')))
phones={'name':names, 'rating':rating, 'd_price':d_price, 'a_price':a_price, 'diff': diff}
df=pd.DataFrame(phones)
df

,name,rating,d_price,a_price,diff
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,"₹39,999","₹40,999",1000
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,"₹39,999","₹40,999",1000
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,"₹49,999","₹1,01,999",52000
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,"₹44,999","₹95,999",51000
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,"₹49,999","₹74,999",25000
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,"₹49,999","₹74,999",25000
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,"₹40,999","₹45,999",5000
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,"₹46,999","₹47,999",1000
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,"₹49,999","₹1,01,999",52000
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,"₹47,349","₹47,999",650
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,"₹38,849","₹47,999",9150
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,"₹44,999","₹95,999",51000
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,"₹49,999","₹57,990",7991
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,"₹47,999","₹57,990",9991
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,"₹48,999",0,48999
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,"₹46,999",0,46999
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,"₹49,999",0,49999
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,"₹46,999","₹48,900",1901
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,"₹49,999",0,49999
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,"₹43,990","₹79,990",36000
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,"₹43,900","₹79,990",36090
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,"₹49,999","₹57,999",8000
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,"₹48,999","₹54,990",5991
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,"₹48,880","₹84,999",36119

In [28]:
# name of job, company, location
with open('indeed jobs.html', 'r', encoding='utf-8') as file:
    content = file.read()
soup = BeautifulSoup(content,'html.parser')
box=soup.find_all('td',class_="resultContent css-1o6lhys eu4oa1w0")
names=[]
company=[]
location=[]
for i in box:
    names.append(i.find('span').text.strip())
    company.append(i.find('span',class_='css-1h7lukg eu4oa1w0').text.strip())
    location.append(i.find('div',class_='css-1restlb eu4oa1w0').text.strip())
jobs={'name':names, 'company':company, 'location':location}
df=pd.DataFrame(jobs)
df

,name,company,location
0,Junior Python Developer,Saltriver Infosystems Pvt Ltd,"Ahmedabad, Gujarat"
1,AI & ML - Trainee,Techify Solutions,"Ahmedabad, Gujarat"
2,Python Developer Fresher,XcelTec,"Ahmedabad, Gujarat"
3,AI ML Python Developer,"Arrow Electronics, Inc.","Ahmedabad, Gujarat"
4,Trainee AI ML,Vrinsoft Technology,"Ahmedabad, Gujarat"
5,Python Developer,Taasha Technologies,"Ahmedabad, Gujarat"
6,AI Engineer,PySquad Informatics LLP,"Ahmedabad, Gujarat"
7,Full Stack Developer Intern,JuniGadi.com,"Ahmedabad, Gujarat"
8,Data Analyst,Anblicks,"Ahmedabad, Gujarat"
9,Python Developer,Sufalam Technologies Private Ltd.,"Ahmedabad, Gujarat"
10,AI & ML Technologies Specialist,Zydus Group,"Ahmedabad, Gujarat"
11,AI/ML Engineer,eSparkBiz Technologies Pvt. Ltd,"Ahmedabad, Gujarat"
12,Python Developer,reverseBits Tech LLP,"Ahmedabad, Gujarat"
13,Python Developer,Albiorix Technology,"Ahmedabad, Gujarat"
14,Python Developer Fresher,Xceltec Interactive Pvt ltd,"Ahmedabad, Gujarat"